description: "Q-DFedAvgM - Verification Test"
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 3
  topology: "custom"
experiment:
  name: "qdfedavgm_verify_test"
  rounds: 5
  epochs: 2
  trainset_size: 3
  seed: 666
  wait_timeout: 10
  dataset:
    source: "huggingface"
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "RandomIIDPartitionStrategy"
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch"
    model_build_fn: "model_build_fn"
    learner_package: "p2pfl.learning.frameworks.pytorch.momentum_learner"
    learner_class: "MomentumLearner"
    params: 
      lr_rate: 0.01
      momentum: 0.9
  aggregator:
    package: "p2pfl.learning.aggregators.qdfedavgm"
    aggregator: "QDFedAvgMAggregator"
    params: 
      bits: 8
settings:
  general:
    disable_ray: False
    grpc_timeout: 120
  heartbeat:
    timeout: 99999
    period: 10
    wait_convergence: 180
  training:
    vote_timeout: 120
    aggregation_timeout: 300
