description: "Centralized MNIST FedAdp Label Skewed"
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 50
  topology: "star"
experiment:
  centralized: true
  name: "centralized_fedadp_mnist_label_skewed"
  rounds: 100
  epochs: 1
  trainset_size: 50
  seed: 666
  wait_timeout: 18000
  dataset:
    source: "huggingface"
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "PathologicalPartitionStrategy"
      params: 
        num_classes_per_node: 2
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch"
    model_build_fn: "model_build_fn"
    params: 
      input_size: 784
      lr_rate: 0.001
  aggregator:
    package: "p2pfl.learning.aggregators.fedadp"
    aggregator: "FedAdp"
    params: 
      alpha: 1.0
settings:
  general:
    log_level: "INFO"
    grpc_timeout: 2
    disable_ray: False
  heartbeat:
    timeout: 99999
  training:
    aggregation_timeout: 300
