description: "MNIST Pathological - Label Skewed"
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 3
  topology: "full"
experiment:
  name: "mnist_pathological"
  rounds: 1
  epochs: 1
  trainset_size: 3
  seed: 666
  wait_timeout: 18000
  dataset:
    source: "huggingface"
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: \"LabelSkewedPartitionStrategy\"`n      params:`n        shards_per_node: 2
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch"
    model_build_fn: "model_build_fn"
    params: 
      lr_rate: 0.001
  aggregator:
    package: "p2pfl.learning.aggregators.dfedadp"
    aggregator: "DFedAdp"
    params: 
      learning_rate: 0.001
      decay_rate: 0.99
      alpha: 1.0
settings:
  heartbeat:
    timeout: 1200
    period: 5

