description: "MNIST Dirichlet 0.1 - Highly Non-IID"
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 3
  topology: \"full\"
experiment:
  name: "mnist_dirichlet_0.1"
  rounds: 1
  epochs: 1
  trainset_size: 3
  seed: 666
  wait_timeout: 18000
  dataset:
    source: "huggingface"
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "DirichletPartitionStrategy"
      params:
        alpha: 0.1
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch"
    model_build_fn: "model_build_fn"
    params: 
      lr_rate: 0.001
  aggregator:
    package: "p2pfl.learning.aggregators.dfedadp"
    aggregator: "DFedAdp"
    params: 
      learning_rate: 0.001
      decay_rate: 0.99
      alpha: 1.0
settings:
  heartbeat:
    timeout: 1200
    period: 5

